export const GET_RANDOM_TEXT = "GET_RANDOM_TEXT";
export const GET_RANDOM_TEXT_LOADING = "GET_RANDOM_TEXT_LOADING";
export const GET_RANDOM_TEXT_SUCCESS = "GET_RANDOM_TEXT_SUCCESS";
export const GET_RANDOM_TEXT_ERROR = "GET_RANDOM_TEXT_ERROR";

export const USER_INPUT = "USER_INPUT";

export const RACE_COMPLETE = "RACE_COMPLETE";
